### ISSUE TITLE
Move the API calls to javascript

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-workflow#5]
As an editor, I need to see changes to digital.gov reflected in Workflow as soon as they are available in the digital.gov API.

**The problem** is that workflow pulls in the digital.gov APIs via `jekyll_get`, which caches the json feeds and builds the pages/views off of those. So the only way to make workflow reflect the most recent updates is to also rebuild workflow.

**The quick solution** is to move the rendering of content via the APIs in Workflow to javascript.

**Comment by kognise** [comment]
I'm on it!

**Comment by kognise** [comment]
Update: currently I've implemented this for the News, Events, Resources, Services and Communities pages. Despite using promises the page seems to slow down quite a lot on bigger pages, especially while loading the data. We might have to implement some sort of lazy loading. **See it live [here &raquo;](https://digitalgov-workflow.netlify.com/)**

**Comment by kognise** [comment]
Update: this is now finished for all pages. I also speeded up loading a lot. **See it live [here &raquo;](https://digitalgov-workflow.netlify.com/)**

**Comment by kognise** [comment]
This is fixed and should probably be closed.
