### ISSUE TITLE
Pull in the New Page editor from digital.gov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-workflow#6]
I need to move the functionality used for creating new posts/pages/events in digital.gov over to the workflow site. https://digital.gov/new-post/ 

It should be moved over as-is and navigation should be created to be able to access these pages.

**Comment by kognise** [comment]
Would having a button to access this on the posts page be acceptable or does it have to be in the navigation header?

**Comment by kognise** [comment]
This is also completed.
